[package]
name = "shrinkshot"
version = "2.0.0"
edition = "2024"
exclude = [
    "setup.sh",
]
license-file = "COPYRIGHT"
description = "Naive content-aware resize utility"
repository = "https://github.com/ern0/shrinkshot"

[dependencies]
image = "0.24"
